# Generated by Django 5.2.1 on 2025-05-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_auditor_user_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auditor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
    ]
