# Generated by Django 5.2.1 on 2025-05-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_unreadmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnreadMessage',
        ),
    ]
