# Generated by Django 5.2.1 on 2025-05-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagereadstatus_message_read_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
    ]
